spring:
  application:
    name: eureka-server
server:
  port: 7002
eureka:
  instance:
    hostname: peer2
  client:
#    fetch-registry: false # 不要在本地缓存注册表信息，因为他是服务注册中心
#    register-with-eureka: false # 程序启动，不要注册通过eureka注册该服务，因为他就是eureka服务端
    service-url:
      defaultZone: http://peer1:7001/eureka